### ISSUE TITLE
Fish Fry Map - Short Term Goals

### ISSUE THREAD

**Issue by connorsb** [CodeForPittsburgh/CodeForPittsburgh.github.io#1]
#2016 Lenten season

_February 10-March 24_
- [X] provide a filtering feature so that users can find fish fries based on lunchtime hours, homemade pierogies, and beer/alcohol availability
- [X] present fish fry placemarks in an aesthetically pleasing and easy-to-interpret format
- [X] retain functionality from existing Google map, namely driving directions, visual styling to show homemade pierogies, and pop-up information when a placemark is clicked

~~\- [ ] provide functionality that allows the map to be updated from a simple format such as a Google sheet or existing Google map KML~~

**Comment by connorsb** [comment]
(populated from this feature list: http://opgh.org/project-fish-fry-map/)

**Comment by gassc** [comment]
Some notes re: implementation are here: https://github.com/openpgh/openpgh.github.io/wiki/Fish-Fry-Map-2016
