### ISSUE TITLE
Fish Fry Map - Long Term Goals

### ISSUE THREAD

**Issue by connorsb** [CodeForPittsburgh/CodeForPittsburgh.github.io#2]
# Due by 2017 Lenten season

_March 1-April 13_
## Data model
- [ ] break out things currently found in description (e.g., when, where, takeout, contact info, website, etc.) into individual attributes, which will support filtering, symbology, and search capability
- [ ] capture dates open so that filtering can be automated (time-aware: next fish fry is highlighted)
- [ ] provide filtering based on organization type (church, fire department, community org., or business)
## Data collection
- [ ] provide a form to collect fish fry data from individuals using intuitive window into above-spec'd data model
- [ ] populate the map directly from user-submitted information
## Hosting
- [ ] ensure that the map can withstand high-volume use
- [ ] automatically populate a Google map for backup
## Design
- [ ] ensure the map is viewable on mobile devices

**Comment by connorsb** [comment]
(populated from this feature list: http://opgh.org/project-fish-fry-map/)

**Comment by gassc** [comment]
This issue was moved to CodeForPittsburgh/fishfrymap#2
