### ISSUE TITLE
Fish Fry Map - Nice to Have

### ISSUE THREAD

**Issue by connorsb** [CodeForPittsburgh/CodeForPittsburgh.github.io#3]
- [ ] “scrape” media listings previously collected by copy-pasting
- [ ] allow users to add photos

**Comment by connorsb** [comment]
(populated from this feature list: http://opgh.org/project-fish-fry-map/)

**Comment by gassc** [comment]
This issue was moved to CodeForPittsburgh/fishfrymap#1
